eureka:
  client:
    register-with-eureka: false
server:
  port: 8060

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: rap-service
            uri: lb://rap-service
            predicates:
              - Path=/api/raps/**
          - id: phongchieu-service
            uri: lb://phongchieu-service
            predicates:
              - Path=/api/phongchieus/**
          - id: phim-service
            uri: lb://phim-service
            predicates:
              - Path=/api/phims/**
          - id: ghe-service
            uri: lb://ghe-service
            predicates:
              - Path=/api/ghes/**
          - id: doidiem-service
            uri: lb://doidiem-service
            predicates:
              - Path=/api/hoadondois/**
          - id: thanhvien-service
            uri: lb://thanhvien-service
            predicates:
              - Path=/api/thanhviens/**
          - id: khunggio-service
            uri: lb://khunggio-service
            predicates:
              - Path=/api/khunggios/**
          - id: dichvu-service
            uri: lb://dichvu-service
            predicates:
              - Path=/api/dichvus/**
          - id: lichchieu-service
            uri: lb://lichchieu-service
            predicates:
              - Path=/api/lichchieus/**
          - id: ve-service
            uri: lb://ve-service
            predicates:
              - Path=/api/ves/**
          - id: hoadon-service
            uri: lb://hoadon-service
            predicates:
              - Path=/api/hoadons/**
          - id: email-service
            uri: lb://email-service
            predicates:
              - Path=/api/emails/**
management:
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    path: /api-docs
