server:
  port: 8087

spring:
  application:
    name: lichchieu-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/quanlyrapphim_lichchieu
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

application:
  config:
    ghes-url: http://localhost:8060/api/ghes
    khunggios-url: http://localhost:8060/api/khunggios
    phims-url: http://localhost:8060/api/phims
    phongchieus-url: http://localhost:8060/api/phongchieus
    raps-url: http://localhost:8060/api/raps

management:
  tracing:
    sampling:
      probability: 1.0

