server:
  port: 8081

spring:
  application:
    name: rap-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/quanlyrapphim_rap
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

application:
  config:
    phongchieus-url: http://localhost:8082/phongchieus

management:
  tracing:
    sampling:
      probability: 1.0

